version: '2'

services:
  search:
    build: './search'
    ports: 
      - '3000:3000'
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  users:
    build: './users'
    ports: 
      - '3001:3000'
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  cars:
    build: './cars'
    ports: 
      - '3002:3000'
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  db:
    image: mongo
    ports:
      - '27017:27017'

  nginx:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cars
      - users
      - search
